In [69]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/stroke-risk-synthetic-2025/stroke_dataset.csv


In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [71]:
df = pd.read_csv("/kaggle/input/stroke-risk-synthetic-2025/stroke_dataset.csv")


In [72]:
df["stroke"].unique()

array([0, 1])

In [73]:
df["gender"].value_counts()

gender
Male      64
Female    62
Name: count, dtype: int64

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 126 non-null    int64  
 1   gender             126 non-null    object 
 2   age                126 non-null    int64  
 3   hypertension       126 non-null    int64  
 4   heart_disease      126 non-null    int64  
 5   ever_married       126 non-null    object 
 6   work_type          126 non-null    object 
 7   Residence_type     126 non-null    object 
 8   avg_glucose_level  126 non-null    float64
 9   bmi                126 non-null    float64
 10  smoking_status     126 non-null    object 
 11  stroke             126 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 11.9+ KB


In [75]:
df=pd.get_dummies(df,columns=["gender","ever_married","work_type","Residence_type","smoking_status"],drop_first=True)
df.head()

id  age  hypertension  heart_disease  avg_glucose_level    bmi  stroke  \
0   1   44             1              0             136.71  29.10       0   
1   2   15             0              0              77.12  27.01       1   
2   3   55             0              0             141.59  22.63       0   
3   4   72             0              0             128.37  14.59       0   
4   5   38             1              0             135.48  28.36       0   

   gender_Male  ever_married_Yes  work_type_Never_worked  work_type_Private  \
0         True              True                   False               True   
1        False              True                   False              False   
2        False              True                    True              False   
3        False              True                    True              False   
4         True             False                   False              False   

   work_type_Self-employed  work_type_children  Residence_type_Urban  \
0                    False               False                  True   
1                     True               False                  True   
2                    False               False                 False   
3                    False               False                 False   
4                    False                True                 False   

   smoking_status_formerly smoked  smoking_status_never smoked  \
0                           False                         True   
1                            True                        False   
2                           False                         True   
3                           False                        False   
4                           False                        False   

   smoking_status_smokes  
0                  False  
1                  False  
2                  False  
3                   True  
4                   True

In [76]:
X = 

SyntaxError: invalid syntax (1712399413.py, line 1)

In [ ]:
X = df.drop("stroke",axis=1)
y= df["stroke"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=15)

In [77]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(max_iter =1000)
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

In [78]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix



score=accuracy_score(y_pred,y_test)
print("score: " , score)
print(classification_report(y_pred,y_test))
print("confusion matrix: \n" , confusion_matrix(y_pred,y_test))

score:  0.7894736842105263
              precision    recall  f1-score   support

           0       0.88      0.81      0.84        26
           1       0.64      0.75      0.69        12

    accuracy                           0.79        38
   macro avg       0.76      0.78      0.77        38
weighted avg       0.80      0.79      0.79        38

confusion matrix: 
 [[21  5]
 [ 3  9]]


In [79]:
model = LogisticRegression()

In [80]:
penalty = ['l1','l2','elasticnet']
c_values = [100,10,0.1,0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg','newton-cholesky', 'sag', 'saga']
params = dict(penalty=penalty,C=c_values,solver=solver)

In [81]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold
cv = StratifiedKFold(n_splits=5)
grid = GridSearchCV(estimator=model,param_grid=params,cv=cv,scoring='accuracy',verbose=1,n_jobs=-1)


In [82]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy', verbose=1)

In [83]:

grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}

In [84]:
grid.best_score_

0.7633986928104575

In [85]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[21  3]
 [ 5  9]]
              precision    recall  f1-score   support

           0       0.81      0.88      0.84        24
           1       0.75      0.64      0.69        14

    accuracy                           0.79        38
   macro avg       0.78      0.76      0.77        38
weighted avg       0.79      0.79      0.79        38

0.7894736842105263
